# https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions
name: Semantic Release
on:
  push:
    branches:
      - main
      - v2
jobs:
  release:
    name: 'Maybe create a Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: 'Install Composer dependencies'
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --optimize-autoloader --classmap-authoritative
          version: "2.x"
          php_version: "7.4" # This should match your "requires_php" value from the Gruntfile.js
      - name: 'Set up Node'
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json' # Uses `engines.node` value!
          cache: 'npm'
      - name: 'Install NPM dependencies'
        run: npm ci --ignore-scripts
      - name: 'Build plugin for release'
        run: npm run release
      - name: 'Run tests'
        run: npm run test
      - name: 'Run semantic-release'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_RELEASE_TOKEN }}
