# https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions
name: Semantic Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: 'Maybe create a Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: 'Set up Node'
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json' # Uses `engines.node` value!
          cache: 'npm'
      - name: 'Install NPM dependencies'
        run: npm ci --ignore-scripts
      - name: 'Run semantic-release'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_RELEASE_TOKEN }}
